import React from "react";
import { Animated, StyleSheet, View } from "react-native";
import { B } from "./data/constants";

// ─── Shell ────────────────────────────────────────────────────────────────────

interface ShellProps {
  children: React.ReactNode;
  accent?: string;
  noPad?: boolean;
  style?: any;
}

export const Shell = ({ children, accent, noPad, style }: ShellProps) => (
  <View
    style={[
      s.shell,
      noPad && { padding: 0 },
      accent && {
        borderColor: accent + "28",
        shadowColor: accent,
        shadowRadius: 22,
        shadowOpacity: 0.15,
        shadowOffset: { width: 0, height: 6 },
      },
      style,
    ]}
  >
    {accent && <View style={[s.shellBar, { backgroundColor: accent }]} />}
    {children}
  </View>
);

// ─── Styles ───────────────────────────────────────────────────────────────────

export const s = StyleSheet.create({
  shell: {
    backgroundColor: B.card,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: B.border,
    padding: 20,
    overflow: "hidden",
    marginBottom: 2,
  },
  shellBar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    borderTopLeftRadius: 24,
    borderBottomLeftRadius: 24,
  },

  // Progress
  progWrap: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: B.border,
  },
  progTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  progTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: B.text,
    letterSpacing: -0.3,
  },
  progSub: { fontSize: 11, color: B.muted, marginTop: 3 },
  progTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.06)",
    overflow: "hidden",
  },
  progFill: { height: 5, borderRadius: 3, backgroundColor: B.primary },
  progPct: { fontSize: 10, color: B.muted2 },
  streakPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "#F59E0B14",
    borderWidth: 1,
    borderColor: "#F59E0B28",
  },
  streakNum: { fontSize: 14, fontWeight: "800", color: B.amber },

  // Card shared
  cardQ: {
    fontSize: 20,
    fontWeight: "800",
    color: B.text,
    letterSpacing: -0.5,
    lineHeight: 28,
    marginBottom: 6,
    marginLeft: 4,
  },
  cardHint: { fontSize: 12, color: B.muted, marginBottom: 16, marginLeft: 4 },

  // Intro
  introIcon: {
    width: 80,
    height: 80,
    borderRadius: 26,
    backgroundColor: B.primary + "20",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: B.primary + "35",
    marginBottom: 22,
  },
  introTitle: {
    fontSize: 26,
    fontWeight: "900",
    color: B.text,
    textAlign: "center",
    letterSpacing: -0.8,
    marginBottom: 14,
    lineHeight: 34,
  },
  introSub: {
    fontSize: 14,
    color: B.muted,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  introStats: { flexDirection: "row", gap: 0, marginBottom: 28, width: "100%" },
  introStat: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: B.border,
    marginHorizontal: 3,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.02)",
  },
  introStatVal: { fontSize: 18, fontWeight: "900", marginBottom: 3 },
  introStatLbl: { fontSize: 10, color: B.muted },
  startBtn: {
    height: 56,
    borderRadius: 18,
    backgroundColor: B.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    shadowColor: B.primary,
    shadowRadius: 18,
    shadowOpacity: 0.45,
    shadowOffset: { width: 0, height: 4 },
  },
  startBtnText: { fontSize: 17, fontWeight: "800", color: "#fff" },

  // Mood
  moodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: B.border,
    backgroundColor: "rgba(255,255,255,0.02)",
    overflow: "hidden",
  },
  moodRowBar: { width: 3, height: 36, borderRadius: 2 },
  moodRowEmoji: { fontSize: 28 },
  moodRowLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: B.text,
    marginBottom: 2,
  },
  moodRowSub: { fontSize: 11, color: B.muted },
  moodCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: B.border,
    alignItems: "center",
    justifyContent: "center",
  },

  // Emotions
  bubbleWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    justifyContent: "center",
    marginTop: 8,
    paddingVertical: 8,
  },
  bubble: { alignItems: "center", justifyContent: "center", borderWidth: 1.5 },
  bubbleText: {
    fontSize: 12,
    color: B.muted,
    fontWeight: "600",
    textAlign: "center",
    paddingHorizontal: 6,
  },
  bubbleSelected: {
    marginTop: 16,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: B.border,
  },
  bubbleSelectedText: { fontSize: 12, color: B.muted, lineHeight: 20 },

  // Energy arc
  arcTapRow: {
    flexDirection: "row",
    gap: 5,
    marginTop: 8,
    justifyContent: "center",
  },
  arcTap: {
    width: 30,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: B.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  arcTapText: { fontSize: 12, color: B.muted },
  energyLegend: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  energyLegendText: { fontSize: 9, color: B.muted2 },

  // Stress thermometer
  thermoTube: {
    width: 22,
    height: 200,
    borderRadius: 11,
    backgroundColor: "rgba(255,255,255,0.06)",
    overflow: "hidden",
    position: "relative",
    justifyContent: "flex-end",
  },
  thermoFill: { width: "100%", borderRadius: 11 },
  thermoTick: {
    position: "absolute",
    right: 0,
    width: 6,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  thermoBulb: { width: 30, height: 30, borderRadius: 15, marginTop: 4 },
  thermoBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 7,
    paddingHorizontal: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "transparent",
    marginBottom: 4,
  },
  thermoCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.06)",
    alignItems: "center",
    justifyContent: "center",
  },
  thermoCircleText: { fontSize: 11, fontWeight: "700", color: B.muted },
  thermoLabel: { fontSize: 13, color: B.muted, flex: 1 },
  thermoFillDot: { width: 6, height: 6, borderRadius: 3 },
  stressTag: { marginTop: 16, padding: 12, borderRadius: 12, borderWidth: 1 },
  stressTagText: { fontSize: 13, fontWeight: "600", lineHeight: 20 },

  // Situation
  sitGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 8 },
  sitTile: {
    alignItems: "center",
    paddingVertical: 14,
    borderRadius: 18,
    borderWidth: 1,
    position: "relative",
  },
  sitCheck: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 14,
    height: 14,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  sitEmoji: { fontSize: 24, marginBottom: 6 },
  sitLabel: { fontSize: 10, color: B.muted, fontWeight: "600" },

  // Question widgets
  qBlock: { borderTopWidth: 1, borderTopColor: B.border, paddingTop: 20 },
  qText: {
    fontSize: 15,
    fontWeight: "700",
    color: B.text,
    lineHeight: 22,
    marginBottom: 14,
  },
  tileGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  tilePick: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: B.border,
    backgroundColor: "rgba(255,255,255,0.03)",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  tileDot: { width: 8, height: 8, borderRadius: 4 },
  tilePickText: { fontSize: 13, color: B.muted },
  ringLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "transparent",
  },
  ringDot: { width: 8, height: 8, borderRadius: 4 },
  ringLabelText: { fontSize: 12, color: B.muted },
  yesNoRow: { flexDirection: "row", gap: 14 },
  yesNoBtn: {
    flex: 1,
    height: 80,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: B.border,
    backgroundColor: "rgba(255,255,255,0.03)",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  yesNoText: { fontSize: 15, fontWeight: "700", color: B.muted },

  // AI Insight
  insightHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  insightAvatar: {
    width: 50,
    height: 50,
    borderRadius: 18,
    backgroundColor: B.primary + "20",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: B.primary + "35",
  },
  insightName: {
    fontSize: 16,
    fontWeight: "800",
    color: B.text,
    marginBottom: 2,
  },
  insightMood: { fontSize: 12, color: B.muted },
  insightLive: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: B.accent,
    shadowColor: B.accent,
    shadowRadius: 6,
    shadowOpacity: 0.9,
    shadowOffset: { width: 0, height: 0 },
  },
  insightQuote: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: B.primary + "25",
  },
  insightQuoteText: {
    fontSize: 14,
    color: B.muted,
    lineHeight: 22,
    fontStyle: "italic",
  },
  insightBarLabel: { fontSize: 12, color: B.muted },
  insightBarVal: { fontSize: 13, fontWeight: "800" },
  insightBarTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: "rgba(255,255,255,0.06)",
    overflow: "hidden",
  },
  insightBarFill: { height: 8, borderRadius: 4 },
  insightBarGlow: {
    height: 8,
    borderRadius: 4,
    position: "absolute",
    opacity: 0.18,
  },
  statePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 20,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
  },
  stateDot: { width: 8, height: 8, borderRadius: 4 },
  stateText: { fontSize: 13, fontWeight: "700" },

  // Submit + grid
  submitBtn: {
    height: 56,
    borderRadius: 18,
    backgroundColor: B.accent,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 20,
    shadowColor: B.accent,
    shadowRadius: 18,
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
  },
  submitBtnText: { fontSize: 17, fontWeight: "800", color: "#fff" },
  savedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 14,
    marginBottom: 16,
  },
  savedIcon: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: B.accent + "20",
    alignItems: "center",
    justifyContent: "center",
  },
  savedTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: B.text,
    marginBottom: 3,
  },
  savedSub: { fontSize: 12, color: B.muted },
  streakRow2: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: B.border,
  },
  streakTitle: { fontSize: 15, fontWeight: "800", color: B.text },
  streakSub: { fontSize: 11, color: B.muted, marginTop: 2 },
  streakBadge2: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: B.amber + "14",
    borderWidth: 1,
    borderColor: B.amber + "30",
  },
  streakBadgeText: { fontSize: 11, fontWeight: "700", color: B.amber },
  divider: { height: 1, backgroundColor: B.border, marginVertical: 18 },
  gridTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: B.text,
    marginBottom: 2,
  },
  gridSub: { fontSize: 11, color: B.muted },
  legendRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 12 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendCell: { width: 11, height: 11, borderRadius: 2 },
  legendText: { fontSize: 10, color: B.muted2 },
  gridDay: { fontSize: 8, color: B.muted2, width: 10, textAlign: "right" },
  monthCard: {
    marginTop: 18,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: B.border,
  },
  monthTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: B.text,
    marginBottom: 12,
  },
  monthStats: { flexDirection: "row", marginBottom: 14 },
  monthStat: { flex: 1, alignItems: "center" },
  monthStatVal: { fontSize: 22, fontWeight: "900", marginBottom: 2 },
  monthStatLbl: { fontSize: 10, color: B.muted },
  monthInsight: { fontSize: 12, color: B.muted, lineHeight: 20 },

  // Navigation
  navWrap: { marginTop: 16, gap: 10 },
  nextBtn: {
    height: 54,
    borderRadius: 16,
    backgroundColor: B.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    shadowColor: B.primary,
    shadowRadius: 14,
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
  },
  nextDisabled: { opacity: 0.35 },
  nextText: { fontSize: 16, fontWeight: "800", color: "#fff" },
  backBtn: { alignSelf: "center", paddingVertical: 10, paddingHorizontal: 20 },
  backText: { fontSize: 13, color: B.muted },
});
